### ISSUE TITLE
Typesetting fails when using lualatex's "--lua" option

### ISSUE THREAD

**Issue by ecofighter** [lualatex/luamplib#97] opened 2021-11-22 13:45 UTC
Typesetting with lua initialization script fails.

foo.lua
``` lua
foo = "foo"
```
test.tex
``` latex
\documentclass{standalone}
\usepackage{luamplib}
\begin{document}
\directlua{tex.sprint(foo)}
\end{document}
```
shell output
```
[~/test][22:29:06]
$ lualatex --lua=foo.lua test.tex
This is LuaHBTeX, Version 1.13.0 (TeX Live 2021/Arch Linux)
 restricted system commands enabled.
(./test.tex
LaTeX2e <2020-10-01> patch level 4
 L3 programming layer <2021-02-18>
(/usr/share/texmf-dist/tex/latex/standalone/standalone.cls
Document Class: standalone 2018/03/26 v1.3a Class to compile TeX sub-files stan
dalone
(/usr/share/texmf-dist/tex/latex/tools/shellesc.sty)
(/usr/share/texmf-dist/tex/generic/iftex/ifluatex.sty
(/usr/share/texmf-dist/tex/generic/iftex/iftex.sty))
(/usr/share/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/share/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/share/texmf-dist/tex/latex/standalone/standalone.cfg)
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texmf-dist/tex/generic/luatex85/luatex85.sty)
(/usr/share/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/usr/share/texmf-dist/tex/generic/infwarerr/infwarerr.sty)
(/usr/share/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)))
(/usr/share/texmf-dist/tex/luatex/luamplib/luamplib.stylstat(./--lua=foo.lua) failed: ./--lua=foo.lua: No such file or directory
kpathsea: Can't get directory of program name: ./--lua=foo.lua
```

luamplib.lua maybe causes this.
I got same error by requring this module.

require.tex
``` latex
\documentclass{standalone}
\begin{document}
\directlua{require("luamplib")}
\end{document}
```
shell output
```
[~/test][22:39:29]
$ lualatex --lua=foo.lua require.tex

...

(/usr/share/texmf-dist/tex/latex/l3backend/l3backend-luatex.def) (./require.aux
) (/usr/share/texmf-dist/tex/latex/base/ts1cmr.fd)lstat(./--lua=foo.lua) failed: ./--lua=foo.lua: No such file or directory
kpathsea: Can't get directory of program name: ./--lua=foo.lua
```
Thanks.

**Comment by dohyunkim** [comment] 2021-11-23 02:11
Thanks for the report.
The issue is fixed in v2.21.1 which is sent to CTAN just now.
Closing.

**Closed by dohyunkim** 2021-11-23 02:11 UTC
